orbs:
  ccidiag:
    description: "If you're running this bad things happened"
    commands:
      run:
        parameters:
          data-dir:
            type: string
            default: "~/.ccidiag"
        steps:
          - run: mkdir << parameters.data-dir >> || exit 0
          - run: dpkg -l > << parameters.data-dir >>/dpkg.log || exit 0
          - run: yarn list > << parameters.data-dir >>/yarn.log || exit 0
          - run: brew list --versions > << parameters.data-dir >>/brew.log || exit 0
          - run: yarn global list > << parameters.data-dir >>/yarn-global.log || exit 0
          - run: gem query --local > << parameters.data-dir >>/gem.log || exit 0
          - run: |
                  npm --version || exit 0
                  npm ls --global > << parameters.data-dir >>/npm-global.log || exit 0
                  npm ls > << parameters.data-dir >>/npm.log || exit 0
          - store_artifacts:
              path: << parameters.data-dir >>
              destination: ccidiag
      metricbeat:
        parameters:
          data-dir:
            type: string
            default: "~/.mb"
        steps:
          - restore_cache:
              keys:
                - v1-metricbeat-6.3.2-linux-x86_64

          - run: |
                mkdir -p << parameters.data-dir >>
                wget -c -nc -O << parameters.data-dir >>/metricbeat.tar.gz https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.3.2-linux-x86_64.tar.gz || exit 0
                tar xzvf << parameters.data-dir>>/metricbeat.tar.gz -C << parameters.data-dir >> --strip-components=1
          - save_cache:
              key: v1-metricbeat-6.3.2-linux-x86_64
              paths:
                - '~/.mb'
          - run:
              background: true
              command: |
                chmod +x << parameters.data-dir >>/metricbeat
                << parameters.data-dir >>/metricbeat -e -E cloud.id="${MBCI}" -E cloud.auth="${ESU}:${ESP}" -c << parameters.data-dir >>/metricbeat.yml


version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-node-browsers

    environment:
      TZ: /usr/share/zoneinfo/America/Los_Angeles
      TRAVIS_REPO_SLUG: facebook/react

    parallelism: 4

    steps:
      - ccidiag/metricbeat
      - checkout

      - run: echo $CIRCLE_COMPARE_URL | cut -d/ -f7

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      - run:
          name: Test Packages
          command: ./scripts/circleci/test_entry_point.sh

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
